PR: Merging gps_main_branch to main_branch
Connected-Healthcare/b_l475e_iot01a_sensors pull request #3
Opened 2021-03-02 01:57 UTC by ganeshram93

Pull Request - GPS module 
1. Interfaced GPS hardware and added the GPS module
2. Handled cases when there is Inactive GPS mode and if GPS hardware stops buffering data - NA will be sent to BT module

![image](https://user-images.githubusercontent.com/19392049/109585021-88f08500-7ab7-11eb-97e5-0501ef7f0c35.png)

2021-03-02 21:33 UTC, coder137 requested changes

2021-03-02 21:33 UTC, coder137 commented on HelloWorld_ST_Sensors/user/gps/gps.cpp
> +        {
Why wait for it to be populated with UART_BUF_LEN?
Check for \n and then parse into latitude/longitude or call the registered_callback function

2021-03-02 21:33 UTC, coder137 commented on HelloWorld_ST_Sensors/user/gps/gps.cpp
> +            if ((GPS_INVALID_NMEA != gps_nmea_type) && (gps_process_fn_ptr != NULL))
I can see that you have handled the case where gps_nmea_type is not valid for our purposes
And you are calling the callback function here. 

But there isn't any parsing logic for the gpgga / gprmc in the else clause.

2021-03-02 21:33 UTC, coder137 commented on HelloWorld_ST_Sensors/user/gps/gps.cpp
> +        {
The second issue with this logic is that below you are taking the entire buffer of 400 characters and checking for only one received type.
Instead get GPS data per line, the above parsing logic would have much fewer if else lines

2021-03-02 21:33 UTC, coder137 commented on HelloWorld_ST_Sensors/user/gps/gps.cpp
> +        {
As mentioned in the interrupt callback, you are iterating over the entire UART_BUF_LEN
But when you receive the first $ value you are parsing that and exiting
There can be multiple $ tokens received we should not need to miss any

2021-03-02 21:33 UTC, coder137 commented on HelloWorld_ST_Sensors/user/gps/gps.cpp
> +    {
Please improve this function, `extract_gpgga_or_gprmc_line` and `gps_interrupt_cb`

Logic should be simple
- Receive one line
- Check if GGA/RMC

- If NO , call registered callback function
- If YES, parse and update lat lon and other data values in the class

2021-03-02 21:33 UTC, coder137 commented on HelloWorld_ST_Sensors/user/gps/gps.hpp
> +            char latitude[15];
latittude, longitude will be double values
lat dir and long dir can be enum values
validity can be a bool value

You can consider making different structs for GGA and RMC

2021-03-02 21:33 UTC, coder137 commented on HelloWorld_ST_Sensors/user/gps/gps.hpp
> +        enum GPS_NMEA_STRING_INDEX_DEFINITION
Will this definition be used by the user? If not put in private

2021-03-02 21:33 UTC, coder137 commented on HelloWorld_ST_Sensors/user/gps/gps.hpp
> +        char curr_line_buffer[UART_BUF_LEN];
Add getters for these variables. Users might accidentally modify this variable unnecessarily

2021-03-02 21:33 UTC, coder137 commented on HelloWorld_ST_Sensors/user/gps/gps.hpp
> +namespace gps_ns
Improve naming

namespace gps
class gps device name. For example 
- gps::ublox_[part_number]
- gps::adafruit_[part_number]

2021-03-02 21:37 UTC, coder137 commented on HelloWorld_ST_Sensors/user/gps/gps.cpp
> +            if ((GPS_INVALID_NMEA != gps_nmea_type) && (gps_process_fn_ptr != NULL))
Okay I realize you might be update the gpgga/gprmc in the `extract_gpgga_or_gprmc_line` function.
Please make the functions concise and limit their scope to one action

2021-03-07 02:48 UTC, ganeshram93 reviewed
Updated PR after comments on first PR: Merging gps_main_branch to main_branch

2021-03-07 02:48 UTC, ganeshram93 commented on HelloWorld_ST_Sensors/user/gps/gps.cpp
> +        {
Resolved in new PR.

2021-03-07 02:48 UTC, ganeshram93 commented on HelloWorld_ST_Sensors/user/gps/gps.cpp
> +    {
Resolved in new PR.

2021-03-07 02:48 UTC, ganeshram93 commented on HelloWorld_ST_Sensors/user/gps/gps.cpp
> +        {
Resolved in new PR.

2021-03-07 02:48 UTC, ganeshram93 commented on HelloWorld_ST_Sensors/user/gps/gps.cpp
> +            if ((GPS_INVALID_NMEA != gps_nmea_type) && (gps_process_fn_ptr != NULL))
Resolved in new PR.

2021-03-07 02:48 UTC, ganeshram93 commented on HelloWorld_ST_Sensors/user/gps/gps.hpp
> +namespace gps_ns
Resolved in new PR.

2021-03-07 02:48 UTC, ganeshram93 commented on HelloWorld_ST_Sensors/user/gps/gps.hpp
> +            char latitude[15];
Resolved in new PR.

2021-03-07 02:48 UTC, ganeshram93 commented on HelloWorld_ST_Sensors/user/gps/gps.hpp
> +        enum GPS_NMEA_STRING_INDEX_DEFINITION
This should not be in private because other GPS modules can make use of the enum and struct.
In the new PR, we have moved the enums and struct to NS, outside the class.

2021-03-07 02:48 UTC, ganeshram93 commented on HelloWorld_ST_Sensors/user/gps/gps.hpp
> +        char curr_line_buffer[UART_BUF_LEN];
It's an enum type, so no need for getters.

2021-03-22 05:39 UTC, coder137 approved these changes

2021-03-22 05:40 UTC, merged